#!/bin/bash
#Pax Flags for Dapper Linux


#------------------------------
# Gnome Shell Flags
#------------------------------
if [ -e /usr/bin/gnome-shell ]
then
    setfattr -n user.pax.flags -v m /usr/bin/gnome-shell
fi
if [ -e /usr/sbin/gdm ]
then
    setfattr -n user.pax.flags -v m /usr/sbin/gdm
fi
if [ -e /usr/bin/gjs-console ]
then
    setfattr -n user.pax.flags -v m /usr/bin/gjs-console
fi
if [ -e /usr/bin/gnome-shell-extension-prefs ]
then
    setfattr -n user.pax.flags -v m /usr/bin/gnome-shell-extension-prefs
fi
if [ -e /usr/libexec/Xorg ]
then
    setfattr -n user.pax.flags -v m /usr/libexec/Xorg
fi
if [ -e /usr/bin/Xwayland ]
then
    setfattr -n user.pax.flags -v m /usr/bin/Xwayland
fi

#------------------------------
# Gnome Application Flags
#------------------------------
if [ -e /usr/libexec/gnome-terminal-server ]
then
    setfattr -n user.pax.flags -v m /usr/libexec/gnome-terminal-server
fi
if [ -e /usr/bin/gnome-control-center ]
then
    setfattr -n user.pax.flags -v m /usr/bin/gnome-control-center
fi
if [ -e /usr/libexec/sushi-start ]
then
    setfattr -n user.pax.flags -v m /usr/libexec/sushi-start
fi
if [ -e /usr/libexec/gnome-session-check-accelerated-gl-helper ]
then
    setfattr -n user.pax.flags -v m /usr/libexec/gnome-session-check-accelerated-gl-helper
fi
if [ -e /usr/libexec/gnome-initial-setup ]
then
    setfattr -n user.pax.flags -v m /usr/libexec/gnome-initial-setup
fi
if [ -e /usr/libexec/webkit2gtk-4.0/WebKitWebProcess ]
then
    setfattr -n user.pax.flags -v m /usr/libexec/webkit2gtk-4.0/WebKitWebProcess
fi


#------------------------------
# Grub Flags
#------------------------------
if [ -e /usr/bin/grub-bios-setup ]
then
    setfattr -n user.pax.flags -v E /usr/bin/grub-bios-setup
fi
if [ -e /usr/sbin/grub-probe ]
then
    setfattr -n user.pax.flags -v E /usr/sbin/grub-probe
fi

#------------------------------
# Calamares Flags
#------------------------------
if [ -e /usr/bin/calamares ]
then
    setfattr -n user.pax.flags -v m /usr/bin/calamares
fi

#------------------------------
# Command Line Application Flags
#------------------------------
if [ -e /usr/bin/elinks ]
then
    setfattr -n user.pax.flags -v m /usr/bin/elinks
fi
if [ -e /usr/bin/glxinfo ]
then
    setfattr -n user.pax.flags -v m /usr/bin/glxinfo
fi
if [ -e /usr/libexec/gstreamer-1.0/gst-plugin-scanner ]
then
    setfattr -n user.pax.flags -v m /usr/libexec/gstreamer-1.0/gst-plugin-scanner
fi

#------------------------------
# Firefox Flags
#------------------------------
if [ -e /usr/lib64/firefox/firefox ]
then
    setfattr -n user.pax.flags -v m /usr/lib64/firefox/firefox
fi
if [ -e /usr/lib64/firefox/firefox-bin ]
then
    setfattr -n user.pax.flags -v m /usr/lib64/firefox/firefox-bin
fi
if [ -e /usr/lib64/firefox/plugin-container ]
then
    setfattr -n user.pax.flags -v m /usr/lib64/firefox/plugin-container
fi

if [ -e /var/lib/flatpak/app/org.mozilla.Firefox/current/active/files/lib/firefox-*/firefox ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/org.mozilla.Firefox/current/active/files/lib/firefox-*/firefox
fi
if [ -e /var/lib/flatpak/app/org.mozilla.Firefox/current/active/files/lib/firefox-*/firefox-bin ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/org.mozilla.Firefox/current/active/files/lib/firefox-*/firefox-bin
fi
if [ -e /var/lib/flatpak/app/org.mozilla.Firefox/current/active/files/lib/firefox-*/plugin-container ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/org.mozilla.Firefox/current/active/files/lib/firefox-*/plugin-container
fi
#------------------------------
# Dapper Hardened Browser Flags
#------------------------------
if [ -e /var/lib/flatpak/app/com.dapperlinux.Dapper-Hardened-Browser/current/active/files/lib/firefox/firefox ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/com.dapperlinux.Dapper-Hardened-Browser/current/active/files/lib/firefox/firefox
fi
if [ -e /var/lib/flatpak/app/com.dapperlinux.Dapper-Hardened-Browser/current/active/files/lib/firefox/firefox-bin ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/com.dapperlinux.Dapper-Hardened-Browser/current/active/files/lib/firefox/firefox-bin
fi
if [ -e /var/lib/flatpak/app/com.dapperlinux.Dapper-Hardened-Browser/current/active/files/lib/firefox/plugin-container ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/com.dapperlinux.Dapper-Hardened-Browser/current/active/files/lib/firefox/plugin-container
fi

#------------------------------
# Gnome Builder Flags
#------------------------------
if [ -e /usr/bin/gnome-builder ]
then
    setfattr -n user.pax.flags -v m /usr/bin/gnome-builder
fi

if [ -e /var/lib/flatpak/app/org.gnome.Builder/current/active/files/bin/gnome-builder ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/org.gnome.Builder/current/active/files/bin/gnome-builder
fi

#------------------------------
# Krita Flags
#------------------------------
if [ -e /usr/bin/krita ]
then
    setfattr -n user.pax.flags -v m /usr/bin/krita
fi

if [ -e /var/lib/flatpak/app/org.kde.krita/current/active/files/bin/krita ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/org.kde.krita/current/active/files/bin/krita
fi

#------------------------------
# Liferea Flags
#------------------------------
if [ -e /usr/bin/liferea ]
then
    setfattr -n user.pax.flags -v m /usr/bin/liferea
fi

#------------------------------
# Libreoffice Flags
#------------------------------
if [ -e /usr/lib64/libreoffice/program/soffice.bin ]
then
    setfattr -n user.pax.flags -v m /usr/lib64/libreoffice/program/soffice.bin
fi

if [ -e /var/lib/flatpak/app/org.libreoffice.LibreOffice/current/active/files/libreoffice/program/soffice.bin ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/org.libreoffice.LibreOffice/current/active/files/libreoffice/program/soffice.bin
fi

#------------------------------
# Minetest Flags
#------------------------------
if [ -e /usr/bin/minetest ]
then
    setfattr -n user.pax.flags -v m /usr/bin/minetest
fi

if [ -e /var/lib/flatpak/app/net.minetest.Minetest/current/active/files/bin/minetest ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/net.minetest.Minetest/current/active/files/bin/minetest
fi

#------------------------------
# Java Flags
#------------------------------
if [ -e /usr/bin/java ]
then
    setfattr -n user.pax.flags -v mr /usr/bin/java
fi
if [ -e /usr/bin/javac ]
then
    setfattr -n user.pax.flags -v mr /usr/bin/javac
fi
if [ -e /usr/bin/javadoc ]
then
    setfattr -n user.pax.flags -v mr /usr/bin/javadoc
fi
if [ -e /usr/bin/jar ]
then
    setfattr -n user.pax.flags -v mr /usr/bin/jar
fi

#------------------------------
# Polari Flags
#------------------------------
if [ -e /usr/bin/polari ]
then
    setfattr -n user.pax.flags -v m /usr/bin/polari
fi

if [ -e /var/lib/flatpak/app/org.gnome.Polari/current/active/files/bin/polari ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/org.gnome.Polari/current/active/files/bin/polari
fi

#------------------------------
# Python Flags
#------------------------------
if [ -e /usr/bin/python2.7 ]
then
    setfattr -n user.pax.flags -v Em /usr/bin/python2.7
fi
if [ -e /usr/bin/python3.6 ]
then
    setfattr -n user.pax.flags -v Em /usr/bin/python3.6
fi

#------------------------------
# Qemu Flags
#------------------------------
if [ -e /usr/bin/qemu-system-i386 ]
then
    setfattr -n user.pax.flags -v m /usr/bin/qemu-system-i386
fi
if [ -e /usr/bin/qemu-system-x86_64 ]
then
    setfattr -n user.pax.flags -v m /usr/bin/qemu-system-x86_64
fi

#------------------------------
# Spotify Flags
#------------------------------
if [ -e /usr/lib64/spotify-client/spotify ]
then
    setfattr -n user.pax.flags -v m /usr/lib64/spotify-client/spotify
fi

if [ -e /var/lib/flatpak/app/com.spotify.Client/current/active/files/extra/share/spotify/spotify ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/com.spotify.Client/current/active/files/extra/share/spotify/spotify
fi

#------------------------------
# Totem Flags
#------------------------------
if [ -e /usr/bin/totem ]
then
    setfattr -n user.pax.flags -v m /usr/bin/totem
fi

if [ -e /var/lib/flatpak/app/org.gnome.Totem/current/active/files/bin/totem ]
then
    setfattr -n user.pax.flags -v m /var/lib/flatpak/app/org.gnome.Totem/current/active/files/bin/totem
fi
#------------------------------
# Thunderbird Flags
#------------------------------
if [ -e /usr/lib64/thunderbird/thunderbird ]
then
    setfattr -n user.pax.flags -v m /usr/lib64/thunderbird/thunderbird
fi
if [ -e /usr/lib64/thunderbird/thunderbird-bin ]
then
    setfattr -n user.pax.flags -v m /usr/lib64/thunderbird/thunderbird-bin
fi
if [ -e /usr/lib64/thunderbird/plugin-container ]
then
    setfattr -n user.pax.flags -v m /usr/lib64/thunderbird/plugin-container
fi

#------------------------------
# Valgrind Flags
#------------------------------
if [ -e /usr/bin/valgrind ]
then
    setfattr -n user.pax.flags -v em /usr/bin/valgrind
fi
if [ -e /usr/lib/valgrind/cachegrind-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/cachegrind-amd64-linux
fi
if [ -e /usr/lib/valgrind/callgrind-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/callgrind-amd64-linux
fi
if [ -e /usr/lib/valgrind/drd-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/drd-amd64-linux
fi
if [ -e /usr/lib/valgrind/exp-bbv-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/exp-bbv-amd64-linux
fi
if [ -e /usr/lib/valgrind/exp-dhat-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/exp-dhat-amd64-linux
fi
if [ -e /usr/lib/valgrind/exp-sgcheck-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/exp-sgcheck-amd64-linux
fi
if [ -e /usr/lib/valgrind/helgrind-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/helgrind-amd64-linux
fi
if [ -e /usr/lib/valgrind/lackey-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/lackey-amd64-linux
fi
if [ -e /usr/lib/valgrind/massif-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/massif-amd64-linux
fi
if [ -e /usr/lib/valgrind/memcheck-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/memcheck-amd64-linux
fi
if [ -e /usr/lib/valgrind/none-amd64-linux ]
then
    setfattr -n user.pax.flags -v em /usr/lib/valgrind/none-amd64-linux
fi
