#!/bin/bash
#Pax Flags for Dapper Linux


#------------------------------
# Gnome Shell Flags
#------------------------------
paxctl -cm /usr/bin/gnome-shell
paxctl -cm /usr/sbin/gdm
paxctl -cm /usr/bin/gjs-console
paxctl -cm /usr/bin/gnome-shell-extension-prefs

#------------------------------
# Gnome Application Flags
#------------------------------
paxctl -cm /usr/libexec/gnome-terminal-server
paxctl -cm /usr/bin/gnome-control-center
paxctl -cm /usr/bin/gnome-builder
paxctl -cm /usr/libexec/sushi-start
paxctl -cm /usr/libexec/gnome-session-check-accelerated-gl-helper
paxctl -cm /usr/libexec/gnome-initial-setup
paxctl -cm /usr/libexec/webkit2gtk-4.0/WebKitWebProcess
paxctl -cm /usr/bin/totem

#------------------------------
# Grub Flags
#------------------------------
paxctl -cE /usr/bin/grub-bios-setup
paxctl -cE /usr/sbin/grub-probe

#------------------------------
# Command Line Application Flags
#------------------------------
paxctl -cm /usr/bin/elinks
paxctl -cm /usr/bin/glxinfo
paxctl -cm /usr/libexec/gstreamer-1.0/gst-plugin-scanner

#------------------------------
# Firefox Flags
#------------------------------
paxctl -cm /usr/lib64/firefox/firefox
paxctl -cm /usr/lib64/firefox/firefox-bin
paxctl -cm /usr/lib64/firefox/plugin-container

#------------------------------
# Dapper Hardened Browser Flags
#------------------------------
paxctl -cm /usr/lib64/dapper-hardened-browser/dapper-hardened-browser
paxctl -cm /usr/lib64/dapper-hardened-browser/dapper-hardened-browser-bin
paxctl -cm /usr/lib64/dapper-hardened-browser/plugin-container

#------------------------------
# Krita Flags
#------------------------------
paxctl -cm /usr/bin/krita

#------------------------------
# Libreoffice Flags
#------------------------------
paxctl -cm /usr/lib64/libreoffice/program/soffice.bin

#------------------------------
# Liferea Flags
#------------------------------
paxctl -cm /usr/bin/liferea

#------------------------------
# Java Flags
#------------------------------
paxctl -cmr /usr/bin/java
paxctl -cmr /usr/bin/javac
paxctl -cmr /usr/bin/jar

#------------------------------
# Python Flags
#------------------------------
paxctl -cEm /usr/bin/python2.7
paxctl -cEm /usr/bin/python3.5

#------------------------------
# Qemu Flags
#------------------------------
paxctl -cm /usr/bin/qemu-system-i386
paxctl -cm /usr/bin/qemu-system-x86_64

#------------------------------
# Spotify Flags
#------------------------------
paxctl -cm /usr/lib64/spotify-client/spotify


#------------------------------
# Thunderbird Flags
#------------------------------
paxctl -cm /usr/lib64/thunderbird/thunderbird
paxctl -cm /usr/lib64/thunderbird/thunderbird-bin
paxctl -cm /usr/lib64/thunderbird/plugin-container

#------------------------------
# Valgrind Flags
#------------------------------
paxctl -cem /usr/bin/valgrind
paxctl -cem /usr/lib/valgrind/cachegrind-amd64-linux
paxctl -cem /usr/lib/valgrind/callgrind-amd64-linux
paxctl -cem /usr/lib/valgrind/drd-amd64-linux
paxctl -cem /usr/lib/valgrind/exp-bbv-amd64-linux
paxctl -cem /usr/lib/valgrind/exp-dhat-amd64-linux
paxctl -cem /usr/lib/valgrind/exp-sgcheck-amd64-linux
paxctl -cem /usr/lib/valgrind/helgrind-amd64-linux
paxctl -cem /usr/lib/valgrind/lackey-amd64-linux
paxctl -cem /usr/lib/valgrind/massif-amd64-linux
paxctl -cem /usr/lib/valgrind/memcheck-amd64-linux
paxctl -cem /usr/lib/valgrind/none-amd64-linux

